---
deployment:
  tasks:
    - export REPOPATH=https://github.com/pavelgitvasilev/common/*
    - export SITEPATH=https://github.com/pavelgitvasilev/common/public
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
